### PR TITLE
ft[landing,contact,about pages]

### PR DESCRIPTION
**Pull request by NIRoberto**
****1. What does this PR do?****

- Display of the landing page,and also the contact page where the one who visit the website can message the owner of web.

**2. Description of Task to be complete**

- Fill i  the form on the button of the web where there is the contact page to call for the web owner.

**3. How should this be manually tested?**

- Clone it to your computer or download a zip file.

- open the index.html file .

**4. Any background context you want to provide?**

**5.What are the relevant Trello story?**

- [trello](url)https://trello.com/b/BZ9zzTTA/user-story

**6.Screenshots (if appropriate)**

add landing page
add contact page
add about page
 [Done!]

### CODE REVIEW

**Review by NIRoberto — COMMENTED** [review]
1. What does this PR do?

- Add user landing page.

- Add contact page

- Add about me page

2. Description of Task to be complete

3. How should this be manually tested?

4. Any background context you want to provide?

5.What are the relevant Trello story?
- [trello](url)https://trello.com/b/BZ9zzTTA/user-story
6.Screenshots (if appropriate)

**Comment by mukunzidd** [comment]
@NIRoberto Please add the above comment in the description.

**Comment by NIRoberto** [comment]
> .

**Comment by NIRoberto** [comment]
.

**Pull request merged**
